apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-rc
spec:
  replicas: 5
  selector:
    app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-ctr
          image: k8s.gcr.io/echoserver:1.10
          ports:
          - containerPort: 8081